### ISSUE TITLE
빌드배틀 메뉴 익셉션

### ISSUE THREAD

**Issue by Bruce0203** [IngGameTeam/inggame#133]
at io.github.inggameteam.mongodb.api.Container.get(Container.kt:86) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.mongodb.api.Container.get(Container.kt:89) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.item.impl.ItemShopMenu$shopMenu$1$1.invoke(ItemShopMenu.kt:46) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.item.impl.ItemShopMenu$shopMenu$1$1.invoke(ItemShopMenu.kt:44) ~[angangang-plugin.jar:?]
        at io.github.monun.invfx.internal.frame.InvFrameImpl.slot(InvFrameImpl.kt:74) ~[?:?]
        at io.github.monun.invfx.internal.frame.InvFrameImpl.slot(InvFrameImpl.kt:41) ~[?:?]
        at io.github.inggameteam.item.impl.ItemShopMenu$shopMenu$1.invoke(ItemShopMenu.kt:44) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.item.impl.ItemShopMenu$shopMenu$1.invoke(ItemShopMenu.kt:38) ~[angangang-plugin.jar:?]
        at io.github.monun.invfx.internal.InvFXSupportImpl.newInvFrame(InvFXSupportImpl.kt:55) ~[?:?]
        at io.github.monun.invfx.InvFX.frame(InvFX.kt:30) ~[?:?]
        at io.github.inggameteam.item.impl.ItemShopMenu.shopMenu(ItemShopMenu.kt:38) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.item.impl.ItemShopMenu.use(ItemShopMenu.kt:29) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.item.api.Interact$DefaultImpls.onInteract(Interact.kt:17) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.item.impl.ItemShopMenu.onInteract(ItemShopMenu.kt:21) ~[angangang-plugin.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor209.execute(Unknown Source) ~[?:?]

**Comment by Bruce0203** [comment]
저 익셉션과 빌드배틀은 상관이 없습니다
