### ISSUE TITLE
월드에딧 익셉션

### ISSUE THREAD

**Issue by Bruce0203** [IngGameTeam/inggame#134]
[18:15:07 ERROR]: [com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent] Catching
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.pollSubmissions(SingleThreadQueueExtent.java:396) ~[FastAsyncWorldEdit-Bukkit.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.getOrCreateChunk(SingleThreadQueueExtent.java:325) ~[FastAsyncWorldEdit-Bukkit.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.getOrCreateChunk(SingleThreadQueueExtent.java:46) ~[FastAsyncWorldEdit-Bukkit.jar:?]
        at com.fastasyncworldedit.core.extent.processor.lighting.NMSRelighter.fixSkyLighting(NMSRelighter.java:1031) ~[FastAsyncWorldEdit-Bukkit.jar:?]
        at com.fastasyncworldedit.core.extent.processor.lighting.NMSRelighter.fixSkyLighting(NMSRelighter.java:979) ~[FastAsyncWorldEdit-Bukkit.jar:?]
        at com.fastasyncworldedit.core.extent.processor.lighting.NMSRelighter.fixLightingSafe(NMSRelighter.java:869) ~[FastAsyncWorldEdit-Bukkit.jar:?]
        at com.fastasyncworldedit.core.extent.processor.lighting.NMSRelighter.removeAndRelight(NMSRelighter.java:103) ~[FastAsyncWorldEdit-Bukkit.jar:?]
        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1298) ~[FastAsyncWorldEdit-Bukkit.jar:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.paste(Clipboard.java:290) ~[FastAsyncWorldEdit-Bukkit.jar:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.paste(Clipboard.java:255) ~[FastAsyncWorldEdit-Bukkit.jar:?]
        at io.github.inggameteam.world.FaweImpl.paste(Fawe.kt:65) ~[angangang-plugin.jar:?]

**Comment by Bruce0203** [comment]
월드에딧을 직접 구현해주시는 것도 고려해볼 수 있을 것 같아요

**Comment by Bruce0203** [comment]
코드를 직접 만들고 하면서 청크가 로드되어 있지 않아서 스키마틱 페이스트가 안되는 문제를 해결할 수도 잇을 것 같아요

**Comment by Bruce0203** [comment]
이 문제는 해결되엇음
