### ISSUE TITLE
mongoldb 에서 sqlite 로 바꿔주세요 

### ISSUE THREAD

**Issue by Bruce0203** [IngGameTeam/inggame#142]

**Comment by Bruce0203** [comment]
sqlite 가 게임 서버 database 로는 가장 이상적인 것 같습니다

**Comment by Bruce0203** [comment]
sqlite 로 코드를 변경하는 과정에서  DTO/VO 가 db pool 객체 변수에 존재하지 않는 버그도 해결될 것 같습니다

**Comment by Bruce0203** [comment]
이것을 구현하는 과정에서 mongodb to sqlite database migration 즉, 유저 데이터 이전이 필요할 것 같다고 생각합니다

**Comment by Bruce0203** [comment]
[22:26:20 WARN]: java.util.ConcurrentModificationException
[22:26:20 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[22:26:20 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[22:26:20 WARN]:        at angangang-plugin.jar//io.github.inggameteam.mongodb.impl.ChallengeContainer.commit(Challenge.kt:50)
[22:26:20 WARN]:        at angangang-plugin.jar//io.github.inggameteam.mongodb.impl.ChallengeContainer.commit(Challenge.kt:24)
[22:26:20 WARN]:        at angangang-plugin.jar//io.github.inggameteam.mongodb.api.Container.commitAndRemove(Container.kt:64)
[22:26:20 WARN]:        at angangang-plugin.jar//io.github.inggameteam.mongodb.api.Container.commitAndRemoveAsync$lambda-3(Container.kt:53)
[22:26:20 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103)
[22:26:20 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:26:20 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)

**Comment by Bruce0203** [comment]
그런데 SQL 쿼리문을 작성하지 않아도 되고 서버가 server/client서버이고 mongodb atlas 로써 데이터 베이스 서버를 따로 둔다는 점에서 더 안전해지니까 sqlite 로 이전하는 것을 취소하고 위 익셉션과 

> sqlite 로 코드를 변경하는 과정에서 DTO/VO 가 db pool 객체 변수에 존재하지 않는 버그도 해결될 것 같습니다

위 버그를 고치는 게 좋을 것 같습니다.

**Comment by Bruce0203** [comment]
추후 C/S DB 보다 SQLite 가 더 나은 상황이 오면 하겠습니다
