### ISSUE TITLE
빌드배틀 익셉션 

### ISSUE THREAD

**Issue by Bruce0203** [IngGameTeam/inggame#71]
그냥 빌드배틀 익셉션 
```java.lang.NullPointerException: null
        at io.github.inggameteam.player.GPlayerRegister.get(GPlayerRegister.kt:32) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.player.GPlayerRegister.get(GPlayerRegister.kt:12) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.player.GPlayerRegister.get(GPlayerRegister.kt:12) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.player.PlayerPlugin$DefaultImpls.get(PlayerPlugin.kt:11) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.player.PlayerPluginImpl.get(PlayerPluginImpl.kt:8) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.minigame.impl.BuildBattle$beginGameTimer$1.invoke(BuildBattle.kt:112) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.minigame.impl.BuildBattle$beginGameTimer$1.invoke(BuildBattle.kt:107) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.scheduler.ITask$Companion.repeat$lambda-0(ITask.kt:31) ~[angangang-plugin.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:531) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Bruce0203** [comment]
해결함
