### ISSUE TITLE
파티 초대 ㅂ그

### ISSUE THREAD

**Issue by Bruce0203** [IngGameTeam/inggame#86]
**버그 설명**
버그가 무엇인지 명확하고 간결한 설명.
`[15:00:57 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'p' in plugin angangang v1.1.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Prismarine-API-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[Prismarine-API-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2390) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2181) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[prismarine-1.18.2.jar:git-Prismarine-"8ae1314"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
        at io.github.inggameteam.party.PartyKt.acceptInvitation$lambda-3(Party.kt:167) ~[angangang-plugin.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at io.github.inggameteam.party.PartyKt.acceptInvitation(Party.kt:167) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.party.PartyUI$1$1$10.invoke(PartyUI.kt:80) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.party.PartyUI$1$1$10.invoke(PartyUI.kt:78) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.command.tree.RootCommandNode.execute(RootCommandNode.kt:20) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.command.CommandDispatcher.execute(CommandDispatcher.kt:11) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.command.MCCommand.onCommand(MCCommand.kt:33) ~[angangang-plugin.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Prismarine-API-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more`

**Comment by Bruce0203** [comment]
고침
