### ISSUE TITLE
파티 모듈 익셉션~

### ISSUE THREAD

**Issue by Bruce0203** [IngGameTeam/inggame#96]
Caused by: java.lang.NullPointerException
        at io.github.inggameteam.party.PartyKt.acceptInvitation(Party.kt:167) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.party.PartyUI$1$1$10.invoke(PartyUI.kt:80) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.party.PartyUI$1$1$10.invoke(PartyUI.kt:78) ~[angangang-plugin.jar:?]
        at io.github.inggameteam.command.tree.RootCommandNode.execute(RootCommandNode.kt:20) ~[angangang-plugin.jar:?]

**Comment by Bruce0203** [comment]
해결함

**Comment by Bruce0203** [comment]
229584ea5467fa0296a58e09e9343ec3e32d9957
